version: '2'
services:
  app:
    build: .
    image: shaunpersad/turner-messenger-test
    command: nodemon start.js
    environment:
      NODE_ENV: development
      PORT: '3000'
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules